# Generated by Django 2.0.5 on 2018-05-03 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupuser',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='signupuser',
            name='email',
            field=models.EmailField(help_text='We will keep you updated about new releases.', max_length=254, verbose_name='Your Email'),
        ),
    ]
